apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_NAME
              value: {{ .Values.env.dbName }}
            - name: DB_USER
              value: {{ .Values.env.dbUser }}
            - name: DB_PORT
              value: {{ .Values.env.dbPort | quote }}
            - name: DB_HOST
              value: {{ .Values.env.dbHost }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-server.fullname" . }}
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-server.fullname" . }}
                  key: JWT_SECRET
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-server.fullname" . }}
                  key: JWT_KEY
          ports:
            - containerPort: {{ .Values.service.port }}
