apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auth-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "auth-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
