apiVersion: v2
name: oms-server
description: A Helm chart for deploying OMS server.
type: application
version: 0.1.0
dependencies:
- name: kong
  repository: "https://charts.konghq.com"
  condition: kong.enabled
  version: "2.42.0"
