apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secret.db | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secret.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
