basePath: /auth
consumes:
    - application/json
definitions:
    GenericError:
        properties:
            message:
                type: string
                x-go-name: Message
        type: object
        x-go-package: github.com/ishtiaqhimel/oms/auth-server/models
    User:
        description: |-
            User represents the user for this application
            swagger: model
        properties:
            Password:
                description: the password for the user
                type: string
            Username:
                description: the name for the user, must be unique
                type: string
                uniqueItems: true
        required:
            - Username
            - Password
        type: object
        x-go-package: github.com/ishtiaqhimel/oms/auth-server/models
info:
    description: Documentation for Auth API
    title: of Auth API
    version: 1.0.0
paths:
    /login:
        post:
            description: Login an user
            operationId: loginUser
            parameters:
                - description: User data structure to SignUp or Login.
                  in: body
                  name: Body
                  required: true
                  schema:
                    $ref: '#/definitions/User'
            responses:
                "200":
                    $ref: '#/responses/noContentResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "401":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - users
    /signup:
        post:
            description: SignUp a new user
            operationId: signupUser
            parameters:
                - description: User data structure to SignUp or Login.
                  in: body
                  name: Body
                  required: true
                  schema:
                    $ref: '#/definitions/User'
            responses:
                "201":
                    $ref: '#/responses/noContentResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - users
produces:
    - application/json
responses:
    errorResponse:
        description: Generic error message returned as a string
        schema:
            $ref: '#/definitions/GenericError'
    noContentResponse:
        description: No content is returned by this API endpoint
schemes:
    - http
swagger: "2.0"
