apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ include "oms-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
username: {{ include "oms-server.fullname" . }}
credentials:
- {{ include "oms-server.fullname" . }}