apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oms-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oms-server.labels" . | nindent 4 }}
  annotations:
    konghq.com/plugins: {{ include "oms-server.fullname" . }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "oms-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
