apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ include "oms-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
plugin: jwt
config:
  claims_to_verify:
    - exp
