apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oms-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oms-server.labels" . | nindent 4 }}
    konghq.com/credential: jwt
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  algorithm: {{ .Values.secret.jwtAlgo | b64enc | quote }}
  secret: {{ .Values.secret.jwtSecret | b64enc | quote }}
  key: {{ .Values.secret.jwtKey | b64enc | quote }}
