apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oms-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oms-server.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
