apiVersion: v1
kind: Service
metadata:
  name: {{ include "oms-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oms-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4000
  selector:
    {{- include "oms-server.selectorLabels" . | nindent 4 }}
